### ISSUE TITLE
FYI: Github installation method needs updating

### ISSUE THREAD

**Issue by pssguy** [metrumresearchgroup/slickR#10]
> devtools::install_github('metrumresearchgroup','slickR')
Downloading GitHub repo slickR/metrumresearchgroup@master
from URL https://api.github.com/repos/slickR/metrumresearchgroup/zipball/master
Installation failed: Not Found (404)

Warning message:
Username parameter is deprecated. Please use slickR/metrumresearchgroup 
> devtools::install_github('metrumresearchgroup/slickR')
Downloading GitHub repo metrumresearchgroup/slickR@master
from URL https://api.github.com/repos/metrumresearchgroup/slickR/zipball/master
Installing slickR

**Comment by yonicd** [comment]
Thanks!
