### ISSUE TITLE
Caption Text 

### ISSUE THREAD

**Issue by DominiqueMakowski** [metrumresearchgroup/slickR#11]
Thanks for your amazing work 😺 

I was wondering if it was possible to add captions on or below the images such as [here](https://www.w3schools.com/howto/howto_js_slideshow.asp)?

Didn't find the answer anywhere...

Thanks a lot!

**Comment by DominiqueMakowski** [comment]
For example yes

**Comment by yonicd** [comment]
this you dont need anything special really. what they do in the link i attached is to create two synchronized sliders, upper is `<img>`, lower is a `<p>...</p>` tag.

this should already be possible in `slickr`

**Comment by DominiqueMakowski** [comment]
I'm sorry, I've definitely no skills in html/js programing so I didn't quite understood how to apply what you suggested. 

Could you maybe  provide a small reproducible example?

Thanks a lot

**Comment by yonicd** [comment]
```r
nba=c("ATL","BKN","BOS","CHA","CHI","CLE","DAL","DEN","DET","GSW","HOU","IND","LAC","LAL","MEM","MIA","MIL","MIN","NOP","NYK","OKC","ORL","PHI","PHX","POR","SAC","SAS","TOR","UTA","WAS")
 
nba_logos=sprintf("https://i.cdn.turner.com/nba/nba/.element/img/4.0/global/logos/512x512/bg.white/svg/%s.svg",nba)

slickR(
obj=c(nba_logos[1:2],'<p>something</p>','<p>something else</p>'),
slideType = c('img','p'),
slideId = c('img','cap'),
slideIdx = list(c(1,2),c(3,4)),
synchSlides = c('img','cap'),
height=100,
slickOpts = list(list(dots=FALSE),list(dots=TRUE,arrows=FALSE))
)
```
