### ISSUE TITLE
variable sizing for synched carousels?

### ISSUE THREAD

**Issue by b-tierney** [metrumresearchgroup/slickR#15]
Is there anyway to have synched carousels where the top images are larger than the bottom?

**Comment by b-tierney** [comment]
Oops, apologies, nevermind I figured it out.

**Comment by elfore** [comment]
@b-tierney Can you tell me how to do it cause I didn't figure it out?

**Comment by yonicd** [comment]
are they regular images or plot outputs?

**Comment by b-tierney** [comment]
I found a height parameter that did the trick for me:

slickR(obj=c(""image1,"image2","image3"),slideType=c('img'),slideId=c('top'),width="100%",slideIdx=list(c(1,2,3)),synchSlides=c('top','bottom'),**height=550**)

slickR(obj=c(""image1,"image2","image3"),slideType=c('img'),slideId=c('bottom'),width="100%",slideIdx=list(c(1,2,3)),synchSlides=c('top','bottom'),**height=200**)

**Comment by yonicd** [comment]
those are synchronized if they are in separate calls?

**Comment by b-tierney** [comment]
yep, they're just in the same column, works great
