### ISSUE TITLE
Error when using slickR in shiny

### ISSUE THREAD

**Issue by cegbuna** [metrumresearchgroup/slickR#16]
Hi,

Thanks for creating this package. Very useful in viewing  images on the fly. 

I've been able to successfully test the package in RStudio but I keep getting the following error when I attempt to use it in a shiny app;

```
Saving a widget with selfcontained = TRUE requires pandoc. For details see:
https://github.com/rstudio/rmarkdown/blob/master/PANDOC.md
```

I did install pandoc but not sure what to do next.

I appreciate any help I can get in resolving this issue.
Thank you.

**Comment by cegbuna** [comment]
Thanks for prompt response. I'll check it out and let you know if I have any questions.

**Comment by cegbuna** [comment]
Hi @yonicd, I was able to test your code and It works. I did use your htmlwidgets example  [here ](https://metrumresearchgroup.github.io/slickR/)to create a shiny app. I was able to create and load a synced carousel but noticed that only the upper htmlwidget (leaflet map) fit into the shinydashboard box. The lower htmlwidget extends outside the box. I have tried to adjust the width and height arguments but nothing seems to work. Do you have any suggestions?

Thank you

**Comment by yonicd** [comment]
do you have a small reproducible example with the dashboard?
