### ISSUE TITLE
Is there a way to display image title/custom text about the image thats being displayed?

### ISSUE THREAD

**Issue by Gannnu** [metrumresearchgroup/slickR#19]
My issue was to find a way to display the image name some where in the shiny app, either on the image or some other place to give viewers a description about the image, but was not able to figure that out.
Being able to display multiple images, it would be nice to add image name/custom text to present more details about that image.

**Comment by yonicd** [comment]
i think this should solve your problem https://github.com/metrumresearchgroup/slickR/issues/11
