### ISSUE TITLE
plotly not working with slickR

### ISSUE THREAD

**Issue by ksakamoto09** [metrumresearchgroup/slickR#22]
I have been trying to use plotly outputs similar to the [example page](https://metrumresearchgroup.github.io/slickR/) but it seems to not be passing in any html from a plotly html file. I can see that it is the same for the example page.

**Comment by yonicd** [comment]
Thank you for opening the issue. I will take a look at how `plotly` is now returning objects.

**Comment by yonicd** [comment]
This is indeed a problem. I am not sure how to solve it though. I will remove those examples for now on the examples page not to create confusion.

thanks again.

**Comment by yonicd** [comment]
this works now (master commit https://github.com/metrumresearchgroup/slickR/commit/79c2579040c23e07da132c36a60ff4c244c14be7)
