### ISSUE TITLE
Enhancement: list of raw images as input

### ISSUE THREAD

**Issue by DavorJ** [metrumresearchgroup/slickR#36]
If images do not reside on the file system, (but somewhere in the database), then saving them to temporary files to feed them to slickR seems the only option?

**Comment by yonicd** [comment]
Thank you for trying the package. 

If I didn’t misunderstand your question. 

You can pass slickR either local files or files on a server via a valid url.

See this vignette for url inputs. https://metrumresearchgroup.github.io/slickR/articles/basics.html

The function itself is also an S3 method (the master branch of the repository) so if you need a special case not supported in the package you can create your own slickR.* function to accommodate your needs.

**Comment by DavorJ** [comment]
Thank you for the tip. I am indeed using a workaround now.

I get my images directly from a database as a RAW vector.

**Comment by yonicd** [comment]
Good to hear. Closing this issue for now. 

If you need more help regarding raw objects feel free to continue posting to this issue.
