### ISSUE TITLE
can this be used to drive a png from visNetwork

### ISSUE THREAD

**Issue by dockstreet** [metrumresearchgroup/slickR#8]
Hi - can images be stored and made clickable, perhaps using crosstalk to change a visNetwork graph in R? 
http://datastorm-open.github.io/visNetwork/nodes.html

i.e. a small graph stored in some sort of store such as rredis and then the carosel used as a history . Then the carosel could be used to drive previous plots of the network graph?

**Comment by yonicd** [comment]
Not quite following, but images in carousel are read from disk (be it persistent or tempfile). What you may mean is having the carousel observable in shiny?

**Comment by dockstreet** [comment]
Thanks for the quick response! 
I was wondering if the carousel could read a blob/raw image from a data frame for display.

Then perhaps be able to click on the image to drive another shiny control such as used as input to a visNetwork graph to serve as running history.

**Comment by yonicd** [comment]
the first part is already possible, see the plots section of the [rendered examples](https://metrumresearchgroup.github.io/slickR/). 

The second part I can add some observers for shiny to pick up.

**Comment by yonicd** [comment]
i added an observer for shiny. you can see how to use it in this [example](https://github.com/metrumresearchgroup/slickR/blob/master/Miscellaneous/shinyTest.R)

**Comment by dockstreet** [comment]
Great work! looks promising for what I want to try out, does it only work in Chrome? I couldn't get it work in IE, not sure if IE has an SVG limitation or not.

**Comment by yonicd** [comment]
no problem. i just pushed another update to add more observers. that should give you more than enough info to use the slider as a reactive object. 

I havent tested this on IE, but no one has raised an issue for it as of yet.

**Comment by dockstreet** [comment]
Hmm... just tried the update, seems like the sprintf code isn't picking up the observables ? has it been renamed?

**Comment by dockstreet** [comment]
so the more observers seems to work, I think there is an issue in IE however? I'll close this and raise it there; thanks again!!!!
