### ISSUE TITLE
IE SVG doesn't seem to render

### ISSUE THREAD

**Issue by dockstreet** [metrumresearchgroup/slickR#9]
IE SVG doesn't seem to render here is a screenshot
![image](https://user-images.githubusercontent.com/1080803/30661566-6fdee69a-9e12-11e7-876d-72d41cd29d55.png)

**Comment by yonicd** [comment]
i dont have access to IE, but I would guess that this is the [solution](https://stackoverflow.com/questions/32870788/css-using-raw-svg-in-the-url-parameter-of-a-background-image-in-ie). 

that is change in  `function(sv)` the header `data:image/svg+xml;utf8,` to what they write.

**Comment by yonicd** [comment]
the question marks also came up on this [closed](https://github.com/metrumresearchgroup/slickR/issues/5) issue

**Comment by dockstreet** [comment]
I haven't fully verified this, but closed this as I believe explanation leads to a workable solution
